import { useMemo, useState } from 'react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { isSupabaseConfigured } from '@/integrations/supabase/client';
import { saveDoc, makeJobKey } from '@/lib/idb';
import { logError } from '@/lib/logging';
import { saveEstimateDocument } from '@/modules/estimate/persistence';

interface DocumentGeneratorProps {
  jobName: string;
  customerAddress: string;
}

export function DocumentGenerator({ jobName, customerAddress }: DocumentGeneratorProps) {
  const [docType, setDocType] = useState<
    | 'Contract'
    | 'Progress Report'
    | 'Coating Notes'
    | 'Line Striping Plan'
    | 'Completion Certificate'
    | 'Before/After Comparison'
  >('Contract');
  const [notes, setNotes] = useState('');
  const [clientName, setClientName] = useState('');
  const [schedule, setSchedule] = useState('');
  const [priceSummary, setPriceSummary] = useState('');

  const title = useMemo(() => `${docType} - ${jobName || 'Job'}`, [docType, jobName]);

  const htmlContent = useMemo(() => {
    return `<!doctype html><html><head><meta charset='utf-8'><title>${title}</title></head><body style="font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial; line-height:1.5;">
      <h1>${title}</h1>
      <p><strong>Client:</strong> ${clientName || 'N/A'}</p>
      <p><strong>Address:</strong> ${customerAddress || 'N/A'}</p>
      <p><strong>Schedule:</strong> ${schedule || 'TBD'}</p>
      <h2>Details</h2>
      <pre>${escapeHtml(notes || '')}</pre>
      ${priceSummary ? `<h2>Pricing Summary</h2><pre>${escapeHtml(priceSummary)}</pre>` : ''}
      <hr/>
      <p style="font-size:12px;color:#666">Generated by Pavement Performance Suite</p>
    </body></html>`;
  }, [title, clientName, customerAddress, schedule, notes, priceSummary]);

  const markdownContent = useMemo(() => {
    return `# ${title}\n\n- **Client**: ${clientName || 'N/A'}\n- **Address**: ${customerAddress || 'N/A'}\n- **Schedule**: ${schedule || 'TBD'}\n\n## Details\n\n${notes || ''}\n\n${priceSummary ? `## Pricing Summary\n\n${priceSummary}` : ''}`;
  }, [title, clientName, customerAddress, schedule, notes, priceSummary]);

  const csvContent = useMemo(() => {
    const rows = [
      ['Title', title],
      ['Client', clientName],
      ['Address', customerAddress],
      ['Schedule', schedule],
      ['Notes', notes.replace(/\n/g, ' ')],
      ['Pricing Summary', priceSummary.replace(/\n/g, ' ')],
    ];
    return rows.map((r) => r.map(csvEscape).join(',')).join('\n');
  }, [title, clientName, customerAddress, schedule, notes, priceSummary]);

  const download = (blob: Blob, filename: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  const exportPdf = () => {
    const win = window.open('', 'print');
    if (!win) return;
    win.document.write(htmlContent);
    win.document.close();
    win.focus();
    win.print();
  };

  const exportDoc = () => {
    // Word-compatible HTML (.doc)
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    download(blob, `${title}.doc`);
  };

  const exportHtml = () => {
    const blob = new Blob([htmlContent], { type: 'text/html' });
    download(blob, `${title}.html`);
  };

  const exportMarkdown = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    download(blob, `${title}.md`);
  };

  const exportCsv = () => {
    const blob = new Blob([csvContent], { type: 'text/csv' });
    download(blob, `${title}.csv`);
  };

  const saveRecord = async () => {
    const jobKey = makeJobKey(jobName, customerAddress);
    await saveDoc(jobKey, title, {
      docType,
      clientName,
      customerAddress,
      schedule,
      notes,
      priceSummary,
      createdAt: new Date().toISOString(),
    });

    if (!isSupabaseConfigured) {
      toast.success('Document saved locally');
      return;
    }

    try {
      await saveEstimateDocument({
        jobName,
        customerAddress,
        title,
        docType,
        htmlContent,
        markdownContent,
        schedule,
        clientName,
        notes,
        priceSummary,
      });
      toast.success('Document synced to mission records');
    } catch (error) {
      toast.error('Document saved locally, but cloud sync failed');
      logError(error, { source: 'document.save', title });
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Document Generator</CardTitle>
        <CardDescription>
          Create client-facing documents and internal records; export in multiple formats.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <Label htmlFor="doc-type">Document Type</Label>
            <select
              id="doc-type"
              className="w-full border rounded-md p-2 bg-background"
              value={docType}
              onChange={(e) => setDocType(e.target.value as any)}
            >
              <option>Contract</option>
              <option>Progress Report</option>
              <option>Coating Notes</option>
              <option>Line Striping Plan</option>
              <option>Completion Certificate</option>
              <option>Before/After Comparison</option>
            </select>
          </div>
          <div>
            <Label htmlFor="client-name">Client Name</Label>
            <Input
              id="client-name"
              value={clientName}
              onChange={(e) => setClientName(e.target.value)}
            />
          </div>
          <div>
            <Label htmlFor="schedule">Schedule</Label>
            <Input
              id="schedule"
              placeholder="e.g., 2025-05-10 morning"
              value={schedule}
              onChange={(e) => setSchedule(e.target.value)}
            />
          </div>
        </div>

        <div>
          <Label htmlFor="details-notes">Details / Notes</Label>
          <Textarea
            id="details-notes"
            rows={6}
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            placeholder="Include before/after notes, repair progress, coat details, striping layout, final completion, comparisons..."
          />
        </div>

        <div>
          <Label htmlFor="pricing-summary">Pricing Summary (optional)</Label>
          <Textarea
            id="pricing-summary"
            rows={3}
            value={priceSummary}
            onChange={(e) => setPriceSummary(e.target.value)}
            placeholder="High-level summary for client (internal breakdown stays private)"
          />
        </div>

        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={exportPdf}>
            Export PDF (Print)
          </Button>
          <Button variant="outline" onClick={exportDoc}>
            Export Word (.doc)
          </Button>
          <Button variant="outline" onClick={exportHtml}>
            Export HTML
          </Button>
          <Button variant="outline" onClick={exportMarkdown}>
            Export Markdown
          </Button>
          <Button variant="outline" onClick={exportCsv}>
            Export CSV (Excel compatible)
          </Button>
          <Button onClick={saveRecord}>Save to Records</Button>
        </div>
      </CardContent>
    </Card>
  );
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function csvEscape(field: string) {
  const needsQuotes = /[",\n]/.test(field);
  const out = field.replace(/"/g, '""');
  return needsQuotes ? `"${out}"` : out;
}
